name: Build Android APK

on:
  push:
    branches: [ "main" ]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '22'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm install
      
    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        distribution: 'zulu'
        java-version: '21'
        
    - name: Sync Capacitor
      run: npx cap sync android
      
    - name: Make gradlew executable
      working-directory: ./android
      run: chmod +x gradlew
      
    - name: Build Release APK
      working-directory: ./android
      run: ./gradlew assembleRelease
      
      - name: Sign Release APK
        uses: r0adkll/sign-android-release@v1
        id: sign_app
        with:
          releaseDirectory: android/app/build/outputs/apk/release
          signingKeyBase64: ${{ secrets.RELEASE_KEYSTORE_BASE64 }}
          alias: ${{ secrets.RELEASE_KEY_ALIAS }}
          keyStorePassword: ${{ secrets.RELEASE_KEYSTORE_PASSWORD }}
          keyPassword: ${{ secrets.RELEASE_KEY_PASSWORD }}
          buildToolsVersion: 34.0.0
      
    - name: Rename APK
      run: mv ${{steps.sign_app.outputs.signedReleaseFile}} android/app/build/outputs/apk/release/tallymate.apk
      
    - name: Publish APK to GitHub Release
      uses: ncipollo/release-action@v1
      with:
        tag: "latest"
        name: "Latest Android APK"
        body: "Automated Android APK build triggered by GitHub Actions."
        artifacts: "android/app/build/outputs/apk/release/tallymate.apk"
        allowUpdates: true
        makeLatest: true
        token: ${{ secrets.GITHUB_TOKEN }}
